version: '3.9'

services:
  app:
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      - MONGOURL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: zcube/bitnami-compat-mongodb
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=rootd
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
