version: '3.9'

services:
  app:
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      - MONGOURL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    restart: always
    image: zcube/bitnami-compat-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local
