version: '3.9'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - MONGOURL=mongodb://db:27017

  db:
    image: zcube/bitnami-compat-mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local
